<?php

return [
    'comics' => [
        [
            "id" => "1",
            "title" => "Action Comics #1000: The Deluxe Edition",
            "description" => "The celebration of 1,000 issues of Action Comics continues with a new, Deluxe Edition of the amazing comic that won raves when it hit comics shops in April! This hardcover includes all the stories from that issue, plus the tale by writer Paul Levitz and artist Neal Adams that appeared in the Action Comics: 80 Years Of Superman hardcover, as well as all the variant covers, design sketches by Jim Lee for Superman’s new look, scripts for the stories, the original art from the lost story featuring art by Curt Swan and more! Plus: a complete reprint of the stories that started it all—the Superman stories Action Comics #1 and 2 from 1938!",
            "thumb" => "https://www.coverbrowser.com/image/action-comics/1-1.jpg",
            "price" => "$19.99",
            "series" => "Action Comics",
            "sale_date" => "2018-10-02",
            "type" => "comic book",
        ],
        [
            "id" => "2",
            "title" => "American Vampire 1976 #1",
            "description" => "America is broken. Trust between the government and the American public has crumbled. Paranoia reigns supreme. It’s 1976, and this is the concluding chapter of the Eisner Award-winning American Vampire! Skinner Sweet has exhausted all efforts to regain his lost immortality. With his powers and purpose gone, he is now determined to go out with a bang. At a seedy motorcycle rally in the desert where he’s closer than ever to his death wish, Pearl Jones and a shocking partner track him down for one last, desperate mission: The force known as the Gray Trader and its minions are tunneling through the bowels of the world to unleash hell on Earth—just in time for America’s bicentennial. With catastrophe looming, it’s up to Skinner and Pearl to reconcile and change the course of history—or die trying. The series that launched the careers of superstars Scott Snyder and Rafael Albuquerque returns for nine final issues and the closing chapter of the legacy of American Vampire.",
            "thumb" => "https://www.panini.it/media/catalog/product/cache/a5b5dd3adfe0d321084804c738f29601/M/1/M1BLLA015ISBN_0.jpg",
            "price" => "$3.99",
            "series" => "American Vampire 1976",
            "sale_date" => "2020-10-06",
            "type" => "comic book",
        ],
        [
            "id" => "3",
            "title" => "Aquaman Vol. 4: Underworld",
            "description" => "Enraged by rumors of Arthur’s survival in the slums of Atlantis, the ruthless King Rath orders the use of ancient Atlantean techno-magic to track down the Aquaman at all costs! But the ex-king Arthur can’t hide for long when his fate collides with that of a mysterious young woman on the run from Rath’s own secret police. Her name: Dolphin. Collects AQUAMAN #25-30.  ",
            "thumb" => "https://media.wired.com/photos/593384dad80dd005b42b2817/master/w_2560%2Cc_limit/Aquaman-16.jpg",
            "price" => "$16.99",
            "series" => "Aquaman",
            "sale_date" => "2018-01-24",
            "type" => "graphic novel",
        ],
        [
            "id" => "4",
            "title" => "Batgirl #1",
            "description" => "“Beyond Burnside” Chapter One: The Batgirl you know and love is going global with Eisner Award-winning and New York Times best-selling writer Hope Larson (A Wrinkle in Time, Goldie Vance) and all-star artist Rafael Albuquerque (AMERICAN VAMPIRE). In order to up her game, Babs travels to Japan on a quest to train with the most elite modern combat masters of the East. But when a chance meeting with an old friend puts a target on her back, Batgirl may need to use her new skills to solve a deadly mystery.",
            "thumb" => "https://d29xot63vimef3.cloudfront.net/image/batgirl/1-1.jpg",
            "price" => "$2.99",
            "series" => "Batgirl",
            "sale_date" => "2016-07-27",
            "type" => "comic book",
        ],
        [
            "id" => "5",
            "title" => "Batman #56",
            "description" => "The Dark Knight’s looking to drop both the hammer and sickle on the KGBeast, whose rampage across Gotham City takes a toll on Nightwing when he’s injured in the fray. Blaming himself for his ward’s fate, Batman gets grimmer than usual—and vows to take the Russian assassin down like the Berlin Wall. Is even Gotham City ready for that much violence? The streets will run red like borscht if the Dark Knight gets his way against this Soviet scourge.",
            "thumb" => "https://static.posters.cz/image/750/locandine-film-in-plexiglass-batman-prowl-comic-cover-i69653.jpg",
            "price" => "$3.99",
            "series" => "Batman",
            "sale_date" => "2018-10-03",
            "type" => "comic book",
        ],
        [
            "id" => "6",
            "title" => "Batman Beyond #1",
            "description" => "“THE RETURN” part one! Terry McGinnis is back as Batman, much to the delight of his family and friends. But is the original Joker really back as well? Inspired by the possible return of their role model, the Jokerz have taken over an entire section of Gotham City and are determined to wreak havoc in the still-rebuilding city. While Batman battles chaos on the streets, his friend Dana is at the mercy of the new leader of the now-unified gang.",
            "thumb" => "https://static.wikia.nocookie.net/marvel_dc/images/5/50/Batman_Beyond_v.1_1.jpg",
            "price" => "$2.99",
            "series" => "Batman Beyond",
            "sale_date" => "2016-10-26",
            "type" => "comic book",
        ],
        [
            "id" => "7",
            "title" => "Batman/Superman #1",
            "description" => "Up in the sky, in the dark of the night, trust no one - for the infected walk among us. Spinning out of the devastating events of THE BATMAN WHO LAUGHS, Superman and Batman are together once more in an all-new monthly series - and they're facing a terrifying new threat that could strike from anywhere. The Dark Knight and the Man of Steel must journey into the depths of Gotham City to learn which of their fellow heroes has been transformed into the horrifying horseman of their most dangerous and deranged foe ever. Our heroes will need to fight to survive, but an even more dangerous question lurkes in the shadows: Can Superman and Batman even trust each other?",
            "thumb" => "https://static.wikia.nocookie.net/marvel_dc/images/0/0d/Batman_Superman_Vol_1_1.jpg",
            "price" => "$3.99",
            "series" => "Batman/Superman",
            "sale_date" => "2019-08-28",
            "type" => "comic book",
        ],
        [
            "id" => "8",
            "title" => "Batman/Superman Annual #1",
            "description" => "On a dark and stormy night in the fifth dimension, two mortal foes meet to settle an age-old question once and for all: In a fight between Batman and Superman, who would win? The combatants? Mr. Mxyzptlk and Bat-Mite. And in this battle for the ages, you will find out if a fifth-dimensional imp can bleed. It’s all in this, the ultimate slugfest between the Dark Knight and the Man of Steel-plus a whole lot of magic!",
            "thumb" => "https://static.wikia.nocookie.net/marvel_dc/images/c/cf/Batman_Superman_Annual_Vol_2_1.jpg",
            "price" => "$4.99",
            "series" => "Batman/Superman Annual",
            "sale_date" => "2020-09-29",
            "type" => "comic book",
        ],
        [
            "id" => "9",
            "title" => "Batman: The Joker War Zone #1",
            "description" => "Gotham City is a battleground as The Joker takes over the Wayne fortune and wages a street war against the Dark Knight and his allies! Enter the “war zone” with short stories featuring characters like Cassandra Cain, Stephanie Brown, and Luke Fox and see how they’re fighting back in a city under siege! Also, the brutal full debut of the mysterious new anti-hero known as Clownhunter!",
            "thumb" => "https://static.wikia.nocookie.net/marvel_dc/images/5/54/Batman_The_Joker_War_Zone_Vol_1_1.jpg",
            "price" => "$5.99",
            "series" => "Batman: The Joker War Zone",
            "sale_date" => "2020-09-29",
            "type" => "comic book",
        ],
        [
            "id" => "10",
            "title" => "Batman: Three Jokers #1",
            "description" => "Thirty years after Batman: The Killing Joke changed comics forever, Three Jokers reexamines the myth of who, or what, The Joker is and what is at the heart of his eternal battle with Batman. New York Times bestselling writer Geoff Johns and Jason Fabok, the writer/artist team that waged the “Darkseid War” in the pages of Justice League, reunite to tell the ultimate story of Batman and The Joker! After years of anticipation starting in DC Universe: Rebirth #1, the epic miniseries you’ve been waiting for is here: find out why there are three Jokers, and what that means for the Dark Knight and the Clown Prince of Crime. It’s a mystery unlike any Batman has ever faced!",
            "thumb" => "https://static.wikia.nocookie.net/marvel_dc/images/6/64/Batman_Three_Jokers_Collected.jpg",
            "price" => "$6.99",
            "series" => "Batman: Three Jokers",
            "sale_date" => "2020-08-25",
            "type" => "comic book",
        ],
        [
            "id" => "11",
            "title" => "Batman: White Knight Presents: Harley Quinn #1",
            "description" => "The Joker is dead, Bruce Wayne is behind bars...and Gotham City is just starting to redefine itself without Batman. As Harley Quinn struggles to adjust to her new life as the mother of Jack Napier’s twins, an elusive mastermind called the Producer seizes the moment to assemble a crew of villains-starting with the Starlet, a serial killer who murders Gotham’s golden age film stars in homage to their silver screen roles. When a recent, gruesome crime scene suggests a connection to The Joker, the GTO, and FBI agent Hector Quimby turn to Harley as the one person with information that could crack the case. With some help from Bruce, Harley agrees to investigate-but to protect her children and her city from a fatal final act, Harley must flirt with madness and confront her own past.",
            "thumb" => "https://static.wikia.nocookie.net/marvel_dc/images/f/f8/Batman_White_Knight_Presents_Harley_Quinn_Vol_1_1.jpg",
            "price" => "$4.99",
            "series" => "Batman: White Knight Presents: Harley Quinn",
            "sale_date" => "2020-10-20",
            "type" => "comic book",
        ],
        [
            "id" => "12",
            "title" => "Catwoman Vol. 1: Copycats",
            "description" => "Following her near-miss wedding with Batman, Catwoman hits the streets to expose a copycat who’s pulling heists around Gotham City. As Selina cracks the whip on her former criminal cohorts, she’s attracting unwanted attention from one of Gotham’s most dangerous groups. The mob? Nope. Try the GCPD. And as if the Bat-Bride didn’t have enough problems, don’t miss the debut of an all-new villain determined to make trouble for all nine of Selina’s lives. Collects issues #1-6 of Catwoman’s new series.",
            "thumb" => "https://static.wikia.nocookie.net/marvel_dc/images/c/c8/Catwoman_Vol_2_1.jpg",
            "price" => "$16.99",
            "series" => "Catwoman",
            "sale_date" => "2019-04-10",
            "type" => "graphic novel",
        ]
    ],

    'movies' => [
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/wVTvfxz53pDqrIvbrxhVdKcLhip.jpg",
            "id" => 9381,
            "original_language" => "en",
            "original_title" => "Babylon A.D.",
            "overview" => "A veteran-turned-mercenary is hired to take a young woman with a secret from post-apocalyptic Eastern Europe to New York City.",
            "popularity" => 199.314,
            "poster_path" => "https://image.tmdb.org/t/p/w342/kt9nqD0uOar8IVE9191HXhWOXKI.jpg",
            "release_date" => "2008-08-20",
            "title" => "Babylon A.D.",
            "video" => false,
            "vote_average" => 5.601,
            "vote_count" => 1906
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/5Di2tovzn8lnXWxigV6xm7yrL24.jpg",
            "id" => 1147400,
            "original_language" => "fr",
            "original_title" => "Miraculous World : Paris, Les Aventures de Toxinelle et Griffe Noire",
            "overview" => "Miraculous holders from another world appear in Paris. They come from a parallel universe where everything is reversed: the holders of Ladybug and Black Cat Miraculouses, Shadybug and Claw Noir, are the bad guys, and the holder of the Butterfly Miraculous, Hesperia, is a superhero. Ladybug and Cat Noir will have to help Hesperia counter the attacks of their evil doubles and prevent them from seizing the Butterfly's Miraculous. Can our heroes also help Hesperia make Shadybug and Claw Noir better people?",
            "popularity" => 78.837,
            "poster_path" => "https://image.tmdb.org/t/p/w342/A46SghdyD9y7qQUxB5zOslospJ7.jpg",
            "release_date" => "2023-10-21",
            "title" => "Miraculous World: Paris, Tales of Shadybug and Claw Noir",
            "video" => false,
            "vote_average" => 6.935,
            "vote_count" => 62
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
            "id" => 507089,
            "original_language" => "en",
            "original_title" => "Five Nights at Freddy's",
            "overview" => "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
            "popularity" => 759.232,
            "poster_path" => "https://image.tmdb.org/t/p/w342/j9mH1pr3IahtraTWxVEMANmPSGR.jpg",
            "release_date" => "2023-10-25",
            "title" => "Five Nights at Freddy's",
            "video" => false,
            "vote_average" => 7.8,
            "vote_count" => 2619
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/6tCTR5Gr91Kocrt0goLrpFs1tqh.jpg",
            "id" => 833326,
            "original_language" => "fr",
            "original_title" => "Rien à foutre",
            "overview" => "Cassandre, 26, is a flight attendant for a low-cost airline. Based in Lanzarote, she’s always willing to take on extra hours and carries out her duties with robotic efficiency. On the side, she just goes with the flow and floats between Tinder, parties and lazy days. When she suddenly gets dismissed, she is forced to return home.",
            "popularity" => 257.363,
            "poster_path" => "https://image.tmdb.org/t/p/w342/wLZ5jijVpOxHuBLmsICKLXwlldu.jpg",
            "release_date" => "2022-03-02",
            "title" => "Zero Fucks Given",
            "video" => false,
            "vote_average" => 6.417,
            "vote_count" => 306
        ],
        [
            "adult" => false,
            "backdrop_path" => null,
            "id" => 461191,
            "original_language" => "en",
            "original_title" => "A",
            "overview" => "A young alcoholic ambient musician locks himself in his apartment on a dangerous seven day bender as he attempts to finish his upcoming album.",
            "popularity" => 3.7,
            "poster_path" => "https://image.tmdb.org/t/p/w342/4uOKZzRB615cIxcVi31pcsdFtSS.jpg",
            "release_date" => "2017-09-13",
            "title" => "A",
            "video" => false,
            "vote_average" => 7.19,
            "vote_count" => 58
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/ltpW5exyTdqL5twV8zRMajf1VgU.jpg",
            "id" => 24791,
            "original_language" => "ja",
            "original_title" => "A",
            "overview" => "Roughly chronological, from 3/96 to 11/96, with a coda in spring of 1997: inside compounds of Aum Shinrikyo, a Buddhist sect led by Shoko Asahara. (Members confessed to a murderous sarin attack in the Tokyo subway in 1995.) We see what they eat, where they sleep, and how they respond to media scrutiny, on-going trials, the shrinking of their fortunes, and the criticism of society. Central focus is placed on Hiroshi Araki, a young man who finds himself elevated to chief spokesman for Aum after its leaders are arrested. Araki faces extreme hostility from the Japanese public, who find it hard to believe that most followers of the cult had no idea of the attacks and even harder to understand why these followers remain devoted to the religion, if not the violence.",
            "popularity" => 4.073,
            "poster_path" => "https://image.tmdb.org/t/p/w342/dBLzrfh5DtxJey1hOYZaN2drPe3.jpg",
            "release_date" => "1998-09-09",
            "title" => "A",
            "video" => false,
            "vote_average" => 6.189,
            "vote_count" => 53
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/A1g8AvP3KpDyu0iyjS6roRxK77v.jpg",
            "id" => 978870,
            "original_language" => "it",
            "original_title" => "L'ultima notte di Amore",
            "overview" => "On the night before his retirement, police lieutenant Franco Amore is called to investigate the death of a long-time partner of his in a diamond heist in which he was involved.",
            "popularity" => 147.052,
            "poster_path" => "https://image.tmdb.org/t/p/w342/dBp0REsZkZ1HK1PycwlLdBtYdsd.jpg",
            "release_date" => "2023-03-09",
            "title" => "Last Night of Amore",
            "video" => false,
            "vote_average" => 7.22,
            "vote_count" => 296
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/kszooR7v1TLFM4pzx6IkKq2jDAN.jpg",
            "id" => 915935,
            "original_language" => "fr",
            "original_title" => "Anatomie d'une chute",
            "overview" => "A woman is suspected of her husband’s murder, and their blind son faces a moral dilemma as the sole witness.",
            "popularity" => 127.384,
            "poster_path" => "https://image.tmdb.org/t/p/w342/kQs6keheMwCxJxrzV83VUwFtHkB.jpg",
            "release_date" => "2023-08-23",
            "title" => "Anatomy of a Fall",
            "video" => false,
            "vote_average" => 7.83,
            "vote_count" => 358
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/5quyXeEA6RaoTjaiypECXOKXT2o.jpg",
            "id" => 1179664,
            "original_language" => "es",
            "original_title" => "Invitación a un Asesinato",
            "overview" => "Eccentric millionaire Olivia sends her half sister Agatha, and a group of old acquaintances, a mysterious invitation for a weekend on her yacht, where they will discover the true motive behind this invitation: the celebration of… a murder?",
            "popularity" => 21.665,
            "poster_path" => "https://image.tmdb.org/t/p/w342/1IFdWd7ykl0yHqKid9Mm7TTIDSK.jpg",
            "release_date" => "2023-10-06",
            "title" => "A Deadly Invitation",
            "video" => false,
            "vote_average" => 5.898,
            "vote_count" => 113
        ],
        [
            "adult" => false,
            "backdrop_path" => null,
            "id" => 116776,
            "original_language" => "ja",
            "original_title" => "ドラゴンボール 魔訶不思議大冒険",
            "overview" => "Master Roshi has succeeded at the one mission he valued most: to train Goku and Krillin to become ultimate fighters. So, he arranges for them to test their mettle at a competition hosted by Emperor Chiaotzu. Not everyone's playing by the rules, however, as a member of the ruler's household schemes to use the Dragonballs to extort money and power from the royal.",
            "popularity" => 296.151,
            "poster_path" => "https://image.tmdb.org/t/p/w342/5aXG0B3TYTpQsodXzvYCkKQfpB1.jpg",
            "release_date" => "1988-07-09",
            "title" => "Dragon Ball: Mystical Adventure",
            "video" => false,
            "vote_average" => 6.756,
            "vote_count" => 227
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
            "id" => 569094,
            "original_language" => "en",
            "original_title" => "Spider-Man: Across the Spider-Verse",
            "overview" => "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
            "popularity" => 323.175,
            "poster_path" => "https://image.tmdb.org/t/p/w342/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
            "release_date" => "2023-05-31",
            "title" => "Spider-Man: Across the Spider-Verse",
            "video" => false,
            "vote_average" => 8.4,
            "vote_count" => 5035
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/3H8u03qr9se2pCv3QTHR1gxSa9k.jpg",
            "id" => 1174725,
            "original_language" => "de",
            "original_title" => "Duell am Abgrund",
            "overview" => "Fearless alpine climbers Ueli Steck and Dani Arnold enter into a death-defying rivalry to set speed records on the Swiss Alps' great north faces.",
            "popularity" => 30.286,
            "poster_path" => "https://image.tmdb.org/t/p/w342/tI9ybrWLiVLljLsNoqEjQF36oG4.jpg",
            "release_date" => "2023-10-04",
            "title" => "Race to the Summit",
            "video" => false,
            "vote_average" => 6.471,
            "vote_count" => 35
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/a2K8ak4pGCHR3O0hMualcokXXpa.jpg",
            "id" => 210763,
            "original_language" => "kn",
            "original_title" => "A",
            "overview" => "A film director fades away from the industry after the failed love with the heroine of his movie. After being rehabilitated, he learns that some people conspired his fall and decides to take revenge.",
            "popularity" => 2.533,
            "poster_path" => "https://image.tmdb.org/t/p/w342/y3DH68oWOGMZ637tqYHfTGU4Bif.jpg",
            "release_date" => "1998-02-12",
            "title" => "A",
            "video" => false,
            "vote_average" => 6.256,
            "vote_count" => 39
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/tvLSz04uSgNyRVdLb8hJDU5uFMB.jpg",
            "id" => 1145810,
            "original_language" => "es",
            "original_title" => "No voy a pedirle a nadie que me crea",
            "overview" => "A writer's career — and entire life — suddenly goes off script when he falls prey to a dangerous web of criminals right before moving to Barcelona.",
            "popularity" => 81.177,
            "poster_path" => "https://image.tmdb.org/t/p/w342/5JyivjFm8WzZU2jhzjMWdbWdOwj.jpg",
            "release_date" => "2023-10-22",
            "title" => "I Don't Expect Anyone to Believe Me",
            "video" => false,
            "vote_average" => 6.0,
            "vote_count" => 4
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/x7x6NT1JcdqxK8GlAWFhm3mzHnV.jpg",
            "id" => 835767,
            "original_language" => "en",
            "original_title" => "Gunfight at Rio Bravo",
            "overview" => "When mysterious Russian gunslinger Ivan Turchin rides into a small Texas town, he runs afoul of a bloodthirsty outlaw gang known as The Hellhounds. Outmanned and outgunned, the town must put their trust in Turchin to protect them from annihilation at the hands of the bandits. The gunslinger finds allies in the form of Marshal Austin Carter and Sheriff Vernon Kelly, and together the three must make a desperate stand against impossible and violent odds.",
            "popularity" => 139.868,
            "poster_path" => "https://image.tmdb.org/t/p/w342/92hYmHw1XpMEF7yZUzjOzcO4zmC.jpg",
            "release_date" => "2023-01-13",
            "title" => "Gunfight at Rio Bravo",
            "video" => false,
            "vote_average" => 4.3,
            "vote_count" => 15
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/uRizG2pUwHNjmTLrUvqdi3pWK1n.jpg",
            "id" => 680133,
            "original_language" => "bn",
            "original_title" => "মুজিব: একটি জাতির রূপকার",
            "overview" => "Biopic on the father of the nation of Bangladesh, Sheikh Mujibur Rahman. The film will showcase his growing up as a child to his standing up against all injustice in his youth to fighting for the independence of his country. How he led a country to it's independence with his inspirational presence and fight for the justice.",
            "popularity" => 44.13,
            "poster_path" => "https://image.tmdb.org/t/p/w342/bnIJ5lK66cfnvJ0A1D6FLp4NZzJ.jpg",
            "release_date" => "2023-10-27",
            "title" => "Mujib: The Making of a Nation",
            "video" => false,
            "vote_average" => 6.1,
            "vote_count" => 5
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/dLfPOTB9zlGCNZJinYvf9yygaX6.jpg",
            "id" => 264859,
            "original_language" => "de",
            "original_title" => "Sechs Schwedinnen auf der Alm",
            "overview" => "This comedy has everyone's favorite 6 Swedish gals enjoying their stay in the alps. When the girls aren't enjoying the pleasure of their own company they're out having a good time with nearly everyone else in town.",
            "popularity" => 74.599,
            "poster_path" => "https://image.tmdb.org/t/p/w342/5kk9GUeeGTdyhcerUfxzhJYt6Gm.jpg",
            "release_date" => "1983-07-22",
            "title" => "Six Swedish Girls in Alps",
            "video" => false,
            "vote_average" => 5.897,
            "vote_count" => 39
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
            "id" => 76600,
            "original_language" => "en",
            "original_title" => "Avatar: The Way of Water",
            "overview" => "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
            "popularity" => 336.921,
            "poster_path" => "https://image.tmdb.org/t/p/w342/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
            "release_date" => "2022-12-14",
            "title" => "Avatar: The Way of Water",
            "video" => false,
            "vote_average" => 7.65,
            "vote_count" => 10266
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/nnkiORKM1Q4AU1eWULI1PiWOTLu.jpg",
            "id" => 1029599,
            "original_language" => "es",
            "original_title" => "Aguila y Jaguar: Los Guerreros Legendarios",
            "overview" => "In a post-apocalyptic future in which water has almost disappeared, two young survivors travel back in time to find the mythical power of the prehispanic God of water, and so be able to create the vital resource. However, when they arrive at the present they discover that the power is in the hands of an unscrupulous businessman who had always wanted to monopolize water and who knows everything about prehispanic myths. The Aztaya brotherhood, a group of heroes, successors from the legendary Aztec and Mayan warriors, will begin the adventure to prevent the villain's plan and help the travelers to change their sad future, teaming up to fight the powerful enemy and his dark allies. To win, the heroes will have to awake the greatest warriors of Aztec and Mayan mythology: The Eagle and the Jaguar.",
            "popularity" => 20.025,
            "poster_path" => "https://image.tmdb.org/t/p/w342/6qR9WbXYIddZcVk6nxFULfHcKmK.jpg",
            "release_date" => "2022-09-29",
            "title" => "Eagle and Jaguar, The Legendary Warriors",
            "video" => false,
            "vote_average" => 6.611,
            "vote_count" => 36
        ],
        [
            "adult" => false,
            "backdrop_path" => "https://image.tmdb.org/t/p/w342/jkKVLzLWjSvTnc84VzeljhSy6j8.jpg",
            "id" => 820525,
            "original_language" => "en",
            "original_title" => "After Everything",
            "overview" => "Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.",
            "popularity" => 212.149,
            "poster_path" => "https://image.tmdb.org/t/p/w342/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg",
            "release_date" => "2023-09-13",
            "title" => "After Everything",
            "video" => false,
            "vote_average" => 7.019,
            "vote_count" => 564
        ]
    ]
];

